version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/monitoring/grafana"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/backups/mongo"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/backups/grafana"
    schedule:
      interval: "weekly"
